### ISSUE TITLE
Some documents appear twice on default advisory list

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#170] opened 2024-06-14 08:05 UTC
ISDuBA: 0.1.1-645-gb54e1e8

Some entries are shown twice in the default list and lead to the same advisory detail page. See the 2+3 and 4+5 table entries in the following screenshot:

![image](https://github.com/ISDuBA/ISDuBA/assets/8190008/b468d0f6-e7e0-437d-838d-44fa95e59eb3)

**Comment by bernhardreiter** [comment] 2024-06-14 11:35
In the above screenshots there are not duplications, sorry for the noise.

The below one shows the problem.
It can be cause by a text search which has two hits within one document and we will address thiss.

![Screenshot 2024-06-13 at 12-03-55 Advisories](https://github.com/ISDuBA/ISDuBA/assets/8190008/3941a7b7-1204-4c2b-ac73-7f27fe489708)

**Comment by koplas** [comment] 2024-06-17 13:23
Documents that contain the search term multiple times will be displayed multiple times. To avoid this, the results have to be grouped.

Here is an example query that is executed when a search term is entered:
```SQL
SELECT
  critical,
  cvss_v3_score,
  cvss_v2_score,
  ssvc,
  state ::text,
  four_cves,
  documents.publisher,
  title,
  documents.tracking_id,
  initial_release_date,
  current_release_date,
  version,
  documents.id,
  ts_headline(
    'german',
    txt,
    websearch_to_tsquery('german', 'money_format')
  )
FROM
  documents
  JOIN advisories ON advisories.tracking_id = documents.tracking_id
  AND advisories.publisher = documents.publisher
  JOIN documents_texts ON id = documents_texts.documents_id
  JOIN unique_texts ON documents_texts.txt_id = unique_texts.id
WHERE
  (
    (
      (
        (
          (
            ts @ @ websearch_to_tsquery('german', 'money_format')
          )
          AND(
            (
              (((tlp) = ('WHITE')))
              OR(((tlp) = ('GREEN')))
            )
          )
        )
      )
      AND(latest)
    )
  )
ORDER BY
  title ASC
LIMIT
  10
```
And here is an example how the query can be changed to avoid duplicates:
```SQL
SELECT
  critical,
  cvss_v3_score,
  cvss_v2_score,
  ssvc,
  state ::text,
  four_cves,
  documents.publisher,
  title,
  documents.tracking_id,
  initial_release_date,
  current_release_date,
  version,
  documents.id,
  ts_headline(
    'german',
    
    -- BEGIN CHANGE
    json_agg(txt),
    -- END CHANGE
    
    websearch_to_tsquery('german', 'money_format')
  )
FROM
  documents
  JOIN advisories ON advisories.tracking_id = documents.tracking_id
  AND advisories.publisher = documents.publisher
  JOIN documents_texts ON id = documents_texts.documents_id
  JOIN unique_texts ON documents_texts.txt_id = unique_texts.id
WHERE
  (
    (
      (
        (
          (
            ts @ @ websearch_to_tsquery('german', 'money_format')
          )
          AND(
            (
              (((tlp) = ('WHITE')))
              OR(((tlp) = ('GREEN')))
            )
          )
        )
      )
      AND(latest)
    )
  )

-- BEGIN CHANGE
GROUP BY
  documents.id,
  advisories.state
-- END CHANGE

ORDER BY
  title ASC
LIMIT
  10
```

**Comment by s-l-teichmann** [comment] 2024-06-17 13:38
The reason is that we currently are not using the full text search the way it should be used. In fact the matching result can be returned by the backend which is currently omitted.  @ThomasJunk and @koplas  we should talk about this.

**Comment by koplas** [comment] 2024-07-15 18:30
I will close this issue, as this is intended behavior.

**Closed** 2024-07-15 18:30 UTC
