### ISSUE TITLE
Update state display to match workflow state

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#269] opened 2024-07-29 09:43 UTC
Currently, switching workflow states works functionally, but the display won't show it until a reload is performed

**Comment by koplas** [comment] 2024-07-29 10:36
Can't reproduce. Please provide the steps needed to reproduce this issue.

**Comment by cintek** [comment] 2024-07-30 08:25
After I've setup a new VM with the setup scripts I can reproduce the issue.

**Comment by cintek** [comment] 2024-07-30 08:44
After using git bisect:
`b3c2f348e52861866ffaa83aab102e979b855105 is the first bad commit`

**Comment by cintek** [comment] 2024-07-30 09:53
It's necessary to run `npm install` after checking out the commit. The bug appears when using `flowbite-svelte` 0.46.0 or higher.

**Comment by cintek** [comment] 2024-07-30 10:11
I don't have a clue what the problem could be. We should switch to version 0.45.1 or do you wan't to try to fix this @koplas? But I wouldn't invest too much time as an upgrade is not necessary yet.

**Comment by koplas** [comment] 2024-07-30 10:55
The issue seems to be here: https://github.com/themesberg/flowbite-svelte/commit/e7cb9d734142c04beef0ecfea485dacf7751c13a#diff-19a080e9a8d04d343b8dee72352ef93924862b0f0c20c506a7099a0a04f85c67R75-R82
In the previous version, the Badge Class was updated on a change.

**Comment by koplas** [comment] 2024-07-30 11:05
Here is the issue: https://github.com/themesberg/flowbite-svelte/issues/1400

**Comment by koplas** [comment] 2024-07-30 19:52
Closing, as this issue is tracked in upstream.

**Closed by koplas** 2024-07-30 19:52 UTC
